### PR TITLE
Fix lag

### PR DESCRIPTION
**Pull request by MuhXd**
something something why main thread

### CODE REVIEW

**Comment by coopeeo** [comment]
please explain, because my dumbass brain has looked at obj-c for too long and broke me.

**Comment by coopeeo** [comment]
i rate obj-c hell/10

**Comment by MuhXd** [comment]
it's just making a new thread for the download index and the other function so it doesn't freeze (testers had this problem)

**Comment by coopeeo** [comment]
oh yea no shit, but doesn't task api do this?

**Comment by MuhXd** [comment]
🤷

**Pull request merged**
